WITH FIRST_GEN AS (
    SELECT ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
),
SECOND_GEN AS (
    SELECT ED.ID, ED.PARENT_ID
    FROM ECOLI_DATA ED
    JOIN FIRST_GEN FG
    ON ED.PARENT_ID = FG.ID
)
SELECT ED.ID
FROM ECOLI_DATA ED
JOIN SECOND_GEN SG
ON ED.PARENT_ID = SG.ID
ORDER BY ED.ID