SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
-- USER_ID, PRODUCT_ID 쌍이 두 개 이상이라는 것은 동일한 회원이 동일한 상품을 재구매 했다는 말과 같음
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(USER_ID) >= 2 
ORDER BY USER_ID ASC, PRODUCT_ID DESC
;
