SELECT DISTINCT a.CAR_ID, a.CAR_TYPE, ROUND((DAILY_FEE * 30 * ((100-DISCOUNT_RATE)/100)), 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR a
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY b ON a.CAR_ID = b.CAR_ID
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN c ON a.CAR_TYPE = c.CAR_TYPE
WHERE a.CAR_TYPE IN ('세단', 'SUV') -- 자동차 종류가 '세단' 또는 'SUV' 인 자동차
AND a.CAR_ID NOT IN 
( -- 2022년 11월에 대여 중인 차
SELECT CAR_ID 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE TO_DATE('2022-11', 'YYYY-MM') BETWEEN START_DATE AND END_DATE 
)
-- 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차
AND DURATION_TYPE = '30일 이상'
AND ROUND((DAILY_FEE * 30 * ((100-DISCOUNT_RATE)/100)), 0) BETWEEN 500000 AND 2000000
ORDER BY 3 DESC, 2, 1 DESC;