SELECT DISTINCT a.CAR_ID, a.CAR_TYPE, ROUND((DAILY_FEE * 30 * ((100-DISCOUNT_RATE)/100)), 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR a
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY b ON a.CAR_ID = b.CAR_ID
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN c ON a.CAR_TYPE = c.CAR_TYPE
WHERE a.CAR_TYPE IN ('세단', 'SUV')
    AND a.CAR_ID NOT IN (
        SELECT CAR_ID 
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE TO_DATE('2022-11', 'YYYY-MM') BETWEEN START_DATE AND END_DATE )
AND DURATION_TYPE = '30일 이상'
AND ROUND((DAILY_FEE * 30 * ((100-DISCOUNT_RATE)/100)), 0) BETWEEN 500000 AND 2000000
ORDER BY 3 DESC, 2, 1 DESC


