SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) TOTAL_SALES
FROM USED_GOODS_USER U
LEFT JOIN USED_GOODS_BOARD B
ON U.USER_ID = B.WRITER_ID
-- WHERE은 그룹 하기 전 조건, HAVING은 그룹한 후 조건
WHERE B.STATUS = 'DONE' -- 완료된 중고 거래
GROUP BY U.USER_ID, U.NICKNAME
HAVING SUM(B.PRICE) >= 700000
ORDER BY SUM(B.PRICE);
