SELECT USER_ID, NICKNAME, CITY || ' ' || STREET_ADDRESS1 || ' ' || STREET_ADDRESS2 AS "전체주소", '010-' || SUBSTR(TLNO, 4, 4) || '-' || SUBSTR(TLNO, 8) AS "TLNO"
FROM USED_GOODS_USER u
WHERE u.USER_ID IN (
SELECT WRITER_ID
FROM USED_GOODS_BOARD b
GROUP BY WRITER_ID
HAVING COUNT(*) >= 3 -- 중고 거래 게시물을 3건 이상 등록한 사용자의 사용자 ID
)
ORDER BY 1 DESC;
