SELECT 
EXTRACT(YEAR FROM SALES_DATE) YEAR, 
EXTRACT(MONTH FROM SALES_DATE) MONTH, 
COUNT(DISTINCT(os.USER_ID)) PURCHASED_USERS,
ROUND(COUNT(DISTINCT(os.USER_ID)) / 
      (SELECT COUNT(USER_ID) FROM USER_INFO WHERE TO_CHAR(JOINED, 'YYYY') = 2021), 1) -- 2021년 가입자 수
      PURCHASED_RATIO
FROM USER_INFO ui
RIGHT JOIN ONLINE_SALE os -- 구매한 이력이 있는 회원만 조회
ON ui.USER_ID = os.USER_ID
WHERE TO_CHAR(JOINED, 'YYYY') = 2021
GROUP BY EXTRACT(YEAR FROM SALES_DATE), EXTRACT(MONTH FROM SALES_DATE)
ORDER BY 1, 2
;
