WITH RECURSIVE ECOLI_GENERATIONS  as (
    # Non-Recursive
    SELECT ID, PARENT_ID, 1 as GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    # Recursive
    SELECT ED.ID, ED.PARENT_ID, ECOLI_GENERATIONS.GENERATION + 1
    FROM ECOLI_GENERATIONS
    JOIN ECOLI_DATA ED
    ON ECOLI_GENERATIONS.ID = ED.PARENT_ID
)

SELECT COUNT(*) COUNT, GENERATION
FROM ECOLI_GENERATIONS
WHERE ID NOT IN (
    SELECT DISTINCT PARENT_ID
    FROM ECOLI_GENERATIONS
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY 2;