SELECT o.PRODUCT_ID, p.PRODUCT_NAME, SUM(AMOUNT * p.PRICE) TOTAL_SALES
FROM FOOD_ORDER o
INNER JOIN FOOD_PRODUCT p
ON o.PRODUCT_ID = p.PRODUCT_ID
WHERE TO_CHAR(o.PRODUCE_DATE, 'YYYY-MM') = '2022-05' -- 생산일자가 2022년 5월인 식품
GROUP BY o.PRODUCT_ID, p.PRODUCT_NAME
ORDER BY 3 DESC, 1;