SELECT c.FLAVOR
FROM (
SELECT a.FLAVOR, SUM(a.TOTAL_ORDER) + SUM(b.TOTAL_ORDER) TOTAL
FROM FIRST_HALF a
INNER JOIN JULY b
ON a.FLAVOR = b.FLAVOR
GROUP BY a.FLAVOR
ORDER BY TOTAL DESC
) c
FETCH FIRST 3 ROWS ONLY;