SELECT APNT_NO, PT_NAME, a.PT_NO, a.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT a
LEFT JOIN PATIENT p
ON a.PT_NO = p.PT_NO
LEFT JOIN DOCTOR d
ON a.MDDR_ID = d.DR_ID
WHERE APNT_CNCL_YN = 'N'
AND TO_CHAR(APNT_YMD, 'YYYY-MM-DD') = '2022-04-13'
ORDER BY 6;

