SELECT HOUR, NVL(COUNT(ao.ANIMAL_ID), 0) COUNT
FROM 
(
SELECT LEVEL - 1 HOUR
FROM DUAL
CONNECT BY LEVEL <= 24
)
LEFT JOIN ANIMAL_OUTS ao
ON HOUR = TO_NUMBER(TO_CHAR(ao.DATETIME, 'HH24')) 
GROUP BY HOUR
ORDER BY 1;