-- SELECT rr.MEMBER_ID, COUNT(rr.MEMBER_ID)
-- FROM REST_REVIEW rr
-- LEFT JOIN MEMBER_PROFILE mp
-- ON rr.MEMBER_ID = mp.MEMBER_ID
-- GROUP BY rr.MEMBER_ID
-- ORDER BY 2 DESC;

SELECT mp.MEMBER_NAME, rr.REVIEW_TEXT, TO_CHAR(rr.REVIEW_DATE, 'YYYY-MM-DD') REVIEW_DATE
FROM REST_REVIEW rr
LEFT JOIN MEMBER_PROFILE mp
ON rr.MEMBER_ID = mp.MEMBER_ID
WHERE rr.MEMBER_ID = (
    SELECT MEMBER_ID -- 리뷰를 제일 많이 쓴 아이디
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(MEMBER_ID) DESC
    FETCH FIRST 1 ROWS ONLY
)
ORDER BY 3, 2

