SELECT TO_CHAR(START_DATE, 'FMMM') MONTH, CAR_ID, COUNT(CAR_ID) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN
(
-- 대여 시작일을 기준으로 2022년 8월부터 2022년 10월까지 총 대여 횟수가 5회 이상인 자동차들
SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE >= TO_DATE('2022-08-01', 'YYYY-MM-DD')
AND START_DATE < TO_DATE('2022-11-01', 'YYYY-MM-DD')
GROUP BY CAR_ID
HAVING COUNT(*) >= 5
)
GROUP BY CAR_ID, TO_CHAR(START_DATE, 'FMMM') -- MONTH가 안됨
HAVING TO_CHAR(START_DATE, 'FMMM') IN ('8', '9', '10')
ORDER BY TO_NUMBER(MONTH), CAR_ID DESC;