WITH MAX_ECOLI AS (
    SELECT YEAR(DIFFERENTIATION_DATE) YEAR, MAX(SIZE_OF_COLONY) MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT YEAR, (MAX_SIZE - SIZE_OF_COLONY) YEAR_DEV, ID
FROM ECOLI_DATA ED
LEFT JOIN MAX_ECOLI ME
ON YEAR(DIFFERENTIATION_DATE) = ME.YEAR
ORDER BY 1, 2;
