SELECT DISTINCT(rh.CAR_ID)
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY rh
LEFT JOIN CAR_RENTAL_COMPANY_CAR c
ON rh.CAR_ID = c.CAR_ID
WHERE CAR_TYPE = '세단' 
AND TO_CHAR(START_DATE, 'YYYY-MM') = '2022-10'
ORDER BY 1 DESC;