WITH FISH_LONGEST AS (
    SELECT ni.FISH_NAME, MAX(LENGTH)
    FROM FISH_INFO i
    LEFT JOIN FISH_NAME_INFO ni
    ON i.FISH_TYPE = ni.FISH_TYPE
    GROUP BY ni.FISH_NAME
)

SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO i
WHERE (FISH_NAME, LENGTH) IN (
    SELECT * FROM FISH_LONGEST l
)