-- 각 타입 별 가장 긴 물고기
WITH FISH_LONGEST AS (
    SELECT FISH_TYPE, MAX(LENGTH)
    FROM FISH_INFO 
    GROUP BY FISH_TYPE
)

SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO
JOIN FISH_NAME_INFO
USING (FISH_TYPE)
WHERE (FISH_TYPE, LENGTH) IN (
    SELECT * FROM FISH_LONGEST
)
ORDER BY ID