SELECT SUM(SCORE) SCORE, e.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES e
LEFT JOIN HR_GRADE g
ON e.EMP_NO = g.EMP_NO
GROUP BY e.EMP_NO, EMP_NAME, DEPT_ID, POSITION, EMAIL
ORDER BY 1 DESC
LIMIT 1;