SELECT '/home/grep/src/' || BOARD_ID || '/' || FILE_ID || FILE_NAME || FILE_EXT FILE_PATH
FROM USED_GOODS_FILE f
WHERE f.BOARD_ID = (
    SELECT board_id
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    FETCH FIRST 1 ROWS ONLY
)
ORDER BY FILE_ID DESC;


